spring:
  application:
    name: currency-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/currency-service/templates
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/spenderdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: testPass
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  port: 1234
  error:
    path: /error


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/