spring:
  application:
    name: web-service
  thymeleaf:
    cache: false
    prefix: classpath:/web/templates
  datasource:
    url: jdbc:postgresql://localhost:5432/spenderdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: helz0407
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  error:
    path: /error
  port: 4321


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/