spring:
  application:
    name: payment-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/payment/templates
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/spenderdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: helz0407
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

server:
  error:
    path: /error
  port: 1222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/